version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "9090:9090"
