version: '3'
services:
  app:
    container_name: backup_solution_container
    image: uallessonivo/db-backup-solution:agrocape
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_GCP_STORAGE_ENABLED=${SPRING_CLOUD_GCP_STORAGE_ENABLED}
      - GOOGLE_STORAGE_PROJECT_ID=${GOOGLE_STORAGE_PROJECT_ID}
      - GOOGLE_STORAGE_BUCKET_NAME=${GOOGLE_STORAGE_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp_account_file.json
      - GOOGLE_APPLICATION_BACKUP_PATH=${GOOGLE_APPLICATION_BACKUP_PATH}
    volumes:
      - "./data:/data"
      - "D:/PROJETOS/dbBackupSolution:/credentials"